# Generated by Django 4.2.1 on 2023-09-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_value',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
