# Generated by Django 4.2.1 on 2023-09-11 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_product_image_back_alter_product_image_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_id',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
